### ISSUE TITLE
Issues with Duplicati plugin

### ISSUE THREAD

**Issue by imnxnyer** [OpenMediaVault-Plugin-Developers/openmediavault-duplicati#2]
With some _aptitude_ management I was able to get Duplicati reliably backing up to Amazon Cloud Drive on OMV2, so I was pleased to discover this plugin after updating to OMV3. Thanks so much for providing this (and supporting the virtualbox plugin).

However with this plugin version I suffer from the problems reported in issue #1. In the (prior) OMV2 install and had to upgrade mono and apparently it's also required on Jessie as described [here](https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono#debian-jessie-80):

> The default Mono version is 3.2.8, which can run Duplicati, but lacks the cert-sync tools. Uninstall any Mono packages and then use the Mono supplied Debian packages, which will give you the latest version of Mono and the ca-certificates-mono package which fixes SSL.

Not sure if you want to tackle that... kind of defeats the goal of stability but after all it is an experimental plugin ;-). 

One more minor issue. After install I subscribed to the experimental channel (via webUI) and updated to 2.0.1.67_canary_2017-06-21.  A day later the OMV Plugin Management offered an "update" to 2.0.1.61-1.  By default Duplicati alerts (via the webUI) to the availability of updated versions so it may not be necessary to monitor the update channel here.

Thanks again!

**Comment by ryecoaaron** [comment]
I tried to get cert-sync to work without adding the mono-project repos but never had any luck.  It is easy enough to add the repo to omv-extras in the repo tab, that I gave up working on this.

I update the packages in the omv-extras repo so people don't get a really old version when installing the plugin.  I didn't test what it would do when you manually update.  That must be something weird duplicati is doing.

**Comment by imnxnyer** [comment]
> It is easy enough to add the repo to omv-extras in the repo tab, that I gave up working on this.
I hadn't of doing it that way, I'll give a try... thanks!

**Comment by kristofejro** [comment]
When I try to install duplicati plugin on my nanopi neo2 with openmediavault I get erros like:

From GUI
```
Reading package lists...
Building dependency tree...
>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --force-yes --fix-missing --allow-unauthenticated --reinstall install openmediavault-duplicati 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openmediavault-duplicati : Depends: duplicati but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
<<< *************************************
```
From console (apt-get install duplicati):

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 duplicati : Depends: mono-runtime (>= 3.0) but it is not installable
             Depends: libmono-2.0-1 but it is not installable
             Depends: libmono-system-core4.0-cil but it is not going to be installed
             Depends: libmono-system-configuration4.0-cil but it is not going to be installed
             Depends: libmono-system-configuration-install4.0-cil but it is not going to be installed
             Depends: libmono-system-data4.0-cil but it is not going to be installed
             Depends: libmono-system-drawing4.0-cil but it is not going to be installed
             Depends: libmono-system-net4.0-cil but it is not going to be installed
             Depends: libmono-system-net-http4.0-cil but it is not going to be installed
             Depends: libmono-system-net-http-webrequest4.0-cil but it is not going to be installed
             Depends: libmono-system-numerics4.0-cil but it is not going to be installed
             Depends: libmono-system-runtime-serialization4.0-cil but it is not going to be installed
             Depends: libmono-system-servicemodel4.0a-cil but it is not going to be installed
             Depends: libmono-system-servicemodel-discovery4.0-cil but it is not going to be installed
             Depends: libmono-system-serviceprocess4.0-cil but it is not going to be installed
             Depends: libmono-system-transactions4.0-cil but it is not going to be installed
             Depends: libmono-system-web4.0-cil but it is not going to be installed
             Depends: libmono-system-web-services4.0-cil but it is not going to be installed
             Depends: libmono-system-xml4.0-cil but it is not going to be installed
             Depends: libmono-microsoft-csharp4.0-cil but it is not going to be installed
             Depends: libappindicator0.1-cil but it is not going to be installed or
                      libappindicator3-0.1-cil but it is not installable
             Depends: gtk-sharp2 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Does anyone of you can tell me why I cannot install duplicati and what to do to solve the problem?

Thanks.

**Comment by ryecoaaron** [comment]
Whatever repo your nanopi is using doesn't have the right mono packages for duplicati.  This is common for arm devices especially if you did not use an OMV image on sourceforge (none for your nanopi).  Nothing we can do to fix this.

**Comment by kristofejro** [comment]
What I have done is:

```
echo "deb http://download.mono-project.com/repo/debian jessie main" | sudo tee /etc/apt/sources.list.d/mono-official.list

apt-get update

apt-get install mono-complete

ln -s /usr/lib/mono /usr/local/lib/

apt-get install duplicati
```

Untill that moment there is no problem nor error.
But then:

```
apt-get install openmediavault-duplicati

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  openmediavault-duplicati
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/6094 B of archives.
After this operation, 17.4 kB of additional disk space will be used.
Selecting previously unselected package openmediavault-duplicati.
(Reading database ... 55568 files and directories currently installed.)
Preparing to unpack .../openmediavault-duplicati_3.0.2_all.deb ...
Unpacking openmediavault-duplicati (3.0.2) ...
Processing triggers for openmediavault (3.0.88) ...
Restarting engine daemon ...
Setting up openmediavault-duplicati (3.0.2) ...
Corlib not in sync with this runtime: expected corlib version 1050700001, found 1050200001.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
Corlib not in sync with this runtime: expected corlib version 1050700001, found 1050200001.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
Processing triggers for openmediavault (3.0.88) ...
Updating locale files ...
Updating file permissions ...
Purging internal cache ...
Restarting engine daemon ...
```
and

```
systemctl status duplicati.service
● duplicati.service
   Loaded: not-found (Reason: No such file or directory)
   Active: failed (Result: exit-code) since Thu 2017-09-21 17:50:00 CEST; 1h 47min ago
 Main PID: 15395 (code=exited, status=1/FAILURE)

Sep 21 17:50:00 openmediavault systemd[1]: Started Duplicati web-server.
Sep 21 17:50:00 openmediavault duplicati-server[15395]: Corlib not in sync with this runtime: expected corlib version 1050700001, found 1050200001.
Sep 21 17:50:00 openmediavault duplicati-server[15395]: Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Sep 21 17:50:00 openmediavault duplicati-server[15395]: Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
Sep 21 17:50:00 openmediavault systemd[1]: duplicati.service: main process exited, code=exited, status=1/FAILURE
Sep 21 17:50:00 openmediavault systemd[1]: Unit duplicati.service entered failed state.
Sep 21 19:27:34 openmediavault systemd[1]: Stopped duplicati.service.
```

Is there any way to solve the problem with mscorlib.dll?
This was done manualy but I have tried to do id via OMV GUI and the result was exactly tha same.

Thanks.

**Comment by ryecoaaron** [comment]
The plugin was modified to work with only the debian jessie versions of mono.  Adding mono-project will use newer and/or different versions and probably doesn't include mozroots.  With OMV 4.x, it is possible that it can use cert-sync which would then possibly work with the mono-project versions for stretch but I haven't tested yet.

All I can suggest is that you use real Debian Jessie without the mono-project repo on your system or just use duplicati without the plugin.

**Comment by kenkendk** [comment]
The mono version in Debian Jessie is 3.8, and the current Mono version is 5.2.
I am not aware of how the OpenMediaVault package/plugin system works, but using the newer Mono 5.2 is bound to cause less trouble:
http://mono-project.com/download#download-lin

If you need to use the 3.8 version, you will have to use `mozroots` as `cert-sync` is only in the newer packages. I have compiled some instructions for setting that up here:
https://github.com/duplicati/duplicati/wiki/SSL-TLS-support-in-Mono

**Comment by ryecoaaron** [comment]
The plugin uses whatever version of mono that the underlying Debian version has in its repos.  I stopped adding mono-project for the plugin since the plugin had to be so different depending on which version of mono was installed.  The current OMV 3.x plugin does use mozroots but maybe I need to include ca-certificates-mono as a dependency.  It would be nice if someone who uses duplicati could maintain the plugin or at least provide pull requests.

**Comment by kristofejro** [comment]
I have already followed instructions from http://mono-project.com
I have mono installed. Its version is: 5.2.0.224-0xamarin3+debian8b1    arm64
Also ca-certificates-mono is installed in the same version.
Duplicati is 2.0.2.8-1.
When running duplicati there is:
```
Corlib not in sync with this runtime: expected corlib version 1050700001, found 1050200001.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```
To be honest I dont know what else I can do.
